"""
Generates a demo hotel inventory (existing portfolio + competitors) for the
DC/MD/VA region.

LIMITATION (documented in docs/data_sources.md): this sandbox cannot reach
OSM Overpass or a licensed hotel directory API. Real deployment replaces this
module with a live OSM `tourism=hotel` pull. Locations here are generated by
clustering around real business districts / attractions (src/ingestion/reference_pois.py)
with randomized jitter and plausible brand/category/room-count distributions,
so the *shape* of the market (density gradients, brand mix) is realistic even
though individual hotel identities are synthetic.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from src.ingestion.reference_pois import BUSINESS_DISTRICTS, ATTRACTIONS

RNG = np.random.default_rng(42)

BRAND_TIERS = {
    "Economy": ["Value Inn", "Roadside Suites", "Budget Stay"],
    "Midscale": ["Comfort Court", "Garden Suites", "Park Place Inn"],
    "Upscale": ["Metro Hotel", "Harbor Suites", "Capital Collection"],
    "Luxury": ["The Grand", "Regency Tower", "The Meridian"],
}
TIER_WEIGHTS = {"Economy": 0.25, "Midscale": 0.40, "Upscale": 0.25, "Luxury": 0.10}
TIER_ROOM_RANGE = {"Economy": (60, 120), "Midscale": (100, 200), "Upscale": (150, 300), "Luxury": (150, 450)}

# "Our" portfolio brand — the fictional client company for this project
PORTFOLIO_BRAND = "Meridian Stay"
PORTFOLIO_TIER_SHARE = {"Economy": 0.30, "Midscale": 0.45, "Upscale": 0.20, "Luxury": 0.05}


def _jitter_point(lat: float, lon: float, spread_km: float) -> tuple[float, float]:
    # ~111 km per degree latitude; longitude scaled by cos(latitude)
    dlat = (RNG.normal(0, spread_km) / 111.0)
    dlon = (RNG.normal(0, spread_km) / (111.0 * np.cos(np.radians(lat))))
    return lat + dlat, lon + dlon


def _sample_tier(weights: dict[str, float]) -> str:
    tiers = list(weights.keys())
    p = np.array(list(weights.values()))
    return RNG.choice(tiers, p=p / p.sum())


