"""
Generates a demo hotel inventory (existing portfolio + competitors) for the
DC/MD/VA region.

LIMITATION (documented in docs/data_sources.md): this sandbox cannot reach
OSM Overpass or a licensed hotel directory API. Real deployment replaces this
module with a live OSM `tourism=hotel` pull. Locations here are generated by
clustering around real business districts / attractions (src/ingestion/reference_pois.py)
with randomized jitter and plausible brand/category/room-count distributions,
so the *shape* of the market (density gradients, brand mix) is realistic even
though individual hotel identities are synthetic.
"""
from __future__ import annotations

