"""
Generates a demo hotel inventory (existing portfolio + competitors) for the
DC/MD/VA region.

LIMITATION (documented in docs/data_sources.md): this sandbox cannot reach
OSM Overpass or a licensed hotel directory API. Real deployment replaces this
module with a live OSM `tourism=hotel` pull. Locations here are generated by
clustering around real business districts / attractions (src/ingestion/reference_pois.py)
with randomized jitter and plausible brand/category/room-count distributions,
so the *shape* of the market (density gradients, brand mix) is realistic even
though individual hotel identities are synthetic.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

from src.ingestion.reference_pois import BUSINESS_DISTRICTS, ATTRACTIONS

RNG = np.random.default_rng(42)

BRAND_TIERS = {
    "Economy": ["Value Inn", "Roadside Suites", "Budget Stay"],
    "Midscale": ["Comfort Court", "Garden Suites", "Park Place Inn"],
    "Upscale": ["Metro Hotel", "Harbor Suites", "Capital Collection"],
    "Luxury": ["The Grand", "Regency Tower", "The Meridian"],
}
TIER_WEIGHTS = {"Economy": 0.25, "Midscale": 0.40, "Upscale": 0.25, "Luxury": 0.10}
TIER_ROOM_RANGE = {"Economy": (60, 120), "Midscale": (100, 200), "Upscale": (150, 300), "Luxury": (150, 450)}

# "Our" portfolio brand — the fictional client company for this project
PORTFOLIO_BRAND = "Meridian Stay"
PORTFOLIO_TIER_SHARE = {"Economy": 0.30, "Midscale": 0.45, "Upscale": 0.20, "Luxury": 0.05}


def _jitter_point(lat: float, lon: float, spread_km: float) -> tuple[float, float]:
    # ~111 km per degree latitude; longitude scaled by cos(latitude)
    dlat = (RNG.normal(0, spread_km) / 111.0)
    dlon = (RNG.normal(0, spread_km) / (111.0 * np.cos(np.radians(lat))))
    return lat + dlat, lon + dlon


def _sample_tier(weights: dict[str, float]) -> str:
    tiers = list(weights.keys())
    p = np.array(list(weights.values()))
    return RNG.choice(tiers, p=p / p.sum())


def generate_hotels(n_hotels: int = 420, portfolio_share: float = 0.12) -> pd.DataFrame:
    """Generate a synthetic hotel market anchored on real business districts/attractions."""
    anchors = BUSINESS_DISTRICTS + [{"name": a["name"], "lat": a["lat"], "lon": a["lon"]} for a in ATTRACTIONS]
    # Weight anchors so downtown DC / dense districts get more hotels (realistic density gradient)
    anchor_weight = np.array([3 if i < len(BUSINESS_DISTRICTS) else 1 for i in range(len(anchors))], dtype=float)
    anchor_weight = anchor_weight / anchor_weight.sum()

    n_portfolio = int(n_hotels * portfolio_share)
    rows = []
    for i in range(n_hotels):
        anchor = anchors[RNG.choice(len(anchors), p=anchor_weight)]
        # Denser cores get tighter clustering; add long-tail spread for suburban hotels
        spread = RNG.choice([1.5, 3.0, 6.0], p=[0.5, 0.3, 0.2])
        lat, lon = _jitter_point(anchor["lat"], anchor["lon"], spread)

        is_portfolio = i < n_portfolio
        tier = _sample_tier(PORTFOLIO_TIER_SHARE if is_portfolio else TIER_WEIGHTS)
        brand = PORTFOLIO_BRAND if is_portfolio else RNG.choice(BRAND_TIERS[tier])
        lo, hi = TIER_ROOM_RANGE[tier]
        rooms = int(RNG.integers(lo, hi))

        rows.append({
            "hotel_id": f"H{i:04d}",
            "name": f"{brand} {anchor['name'].split(',')[0].split('(')[0].strip()}"[:60],
            "brand": brand,
            "is_portfolio": is_portfolio,
            "tier": tier,
            "rooms": rooms,
            "lat": round(lat, 5),
            "lon": round(lon, 5),
            "near_anchor": anchor["name"],
        })

    df = pd.DataFrame(rows)
    return df


if __name__ == "__main__":
    df = generate_hotels()
    out = "data/processed/hotels.parquet"
    df.to_parquet(out, index=False)
    print(f"Generated {len(df)} hotels ({df['is_portfolio'].sum()} portfolio) -> {out}")
    print(df['tier'].value_counts())
